### ISSUE TITLE
redeclared in this block

### ISSUE THREAD

**Issue by wouafff** [ElasticEmail/elasticemail-go#1]
Hi,
I can't build...

` go build
# github.com/elasticemail/elasticemail-go
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_campaign_status.go:25:2: ACTIVE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_account_status_enum.go:27:2: other declaration of ACTIVE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_compression_format.go:24:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_hist_event_type.go:37:2: DELETED redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_campaign_status.go:24:2: other declaration of DELETED
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_status.go:26:2: ACTIVE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_account_status_enum.go:27:2: other declaration of ACTIVE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_status.go:27:2: BOUNCED redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_hist_event_type.go:26:2: other declaration of BOUNCED
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_status.go:28:2: UNSUBSCRIBED redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_hist_event_type.go:27:2: other declaration of UNSUBSCRIBED
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_delivery_optimization_type.go:24:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_email_validation_status.go:24:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_email_validation_status.go:26:2: UNKNOWN redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_consent_tracking.go:24:2: other declaration of UNKNOWN
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_encoding_type.go:25:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_encoding_type.go:25:2: too many errors`

**Comment by pourcheragh** [comment]
It seems this repository is no longer maintained so I created a new repository with the fix [here](https://github.com/pourcheragh/elasticemail-go).

**Comment by radzawee** [comment]
We have just released a new version.
